import type { Metadata } from "next";
import "./globals.css";
import HeaderInfo from "./components/HeaderInfo";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Exclusive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="poppins-regular">
        <HeaderInfo />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
